name: Lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install eslint with GNOME config
        run: npm install --no-save eslint@8 @eslint/js

      - name: Lint
        run: npx eslint --no-eslintrc --config https://gitlab.gnome.org/GNOME/gnome-shell/-/raw/main/.eslintrc.json extension.js widgets/*.js prefs.js
